-- CreateTable
CREATE TABLE "PlaySession" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "date" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "players" TEXT NOT NULL,
    "notes" TEXT NOT NULL DEFAULT '',
    "gameId" INTEGER NOT NULL,
    CONSTRAINT "PlaySession_gameId_fkey" FOREIGN KEY ("gameId") REFERENCES "Game" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
